"""Sample distributions into Spark RDD partitions.

The functions require a PySpark ``SparkContext`` and its RDD APIs.  They
broadcast or pickle the supplied distribution, construct one sampler per
partition seed, and produce independent samples within that partition.  The
helpers neither fit nor score distributions; they are distributed sampling
adapters.  Reproducibility is scoped to the supplied seed, partition count,
and Spark partition execution order.
"""

import pickle
from typing import Any, Optional

import numpy as np
from numpy.random import RandomState
from pyspark import SparkContext

from dmx.arithmetic import maxrandint
from dmx.stats.pdist import SequenceEncodableProbabilityDistribution


def take_sample(
    rdd: Any,
    with_replacement: bool,
    n: int,
    seed: Optional[int] = None,
) -> list[Any]:
    """Take an ordered random sample from an RDD.

    Args:
        rdd: Input RDD supporting ``zipWithUniqueId`` and ``takeSample``.
        with_replacement: Whether sampling is performed with replacement.
        n: Requested sample size.
        seed: Optional seed for sampling and output shuffling.

    Returns:
        Locally collected records, randomly reordered after sampling.
    """
    rng = RandomState(seed)
    sample = rdd.zipWithUniqueId().takeSample(
        with_replacement, n, rng.randint(0, maxrandint)
    )
    sidx = np.argsort([u[1] for u in sample])
    sample = [sample[i][0] for i in sidx]
    sidx = np.argsort(rng.uniform(size=n))
    return [sample[i] for i in sidx]


def sample_seq_as_rdd(
    sc: SparkContext,
    dist: SequenceEncodableProbabilityDistribution,
    seq_len: int,
    count_per_split: int,
    num_splits: int,
    seed: Optional[int] = None,
) -> Any:
    """Sample fixed-length sequences into a partitioned RDD.

    Args:
        sc: Spark context that creates and broadcasts the work.
        dist: Distribution whose sampler implements ``sample_seq``.
        seq_len: Length of each sampled sequence.
        count_per_split: Sequences generated by each partition.
        num_splits: Number of output partitions.
        seed: Optional base seed expanded into partition-local seeds.

    Returns:
        An RDD containing ``count_per_split * num_splits`` sequences.
    """
    distB = sc.broadcast(dist)
    seeds = RandomState(seed).randint(0, maxrandint, size=num_splits)

    def fmap(u: Any) -> Any:
        ddist = distB.value
        sampler: list[Any] = [ddist.sampler(seed=h) for h in u]
        return iter(
            [v for h in sampler for v in h.sample_seq(seq_len, size=count_per_split)]
        )

    return sc.parallelize(seeds, num_splits).mapPartitions(fmap, True)


def sample_rdd(
    sc: SparkContext,
    dist: SequenceEncodableProbabilityDistribution,
    count_per_split: int,
    num_splits: int,
    seed: Optional[int] = None,
) -> Any:
    """Sample independent observations into a partitioned RDD.

    Args:
        sc: Spark context that creates and broadcasts the work.
        dist: Distribution whose sampler implements ``sample``.
        count_per_split: Observations generated by each partition.
        num_splits: Number of output partitions.
        seed: Optional base seed expanded into partition-local seeds.

    Returns:
        An RDD containing ``count_per_split * num_splits`` observations.
    """
    dd = pickle.dumps(dist, protocol=0)
    distB = sc.broadcast(dd)
    seeds = RandomState(seed).randint(0, maxrandint, size=num_splits)

    def fmap(u: Any) -> Any:
        ddist = pickle.loads(distB.value)
        sampler: list[Any] = [ddist.sampler(seed=h) for h in u]
        return iter([v for h in sampler for v in h.sample(size=count_per_split)])

    return sc.parallelize(seeds, num_splits).mapPartitions(fmap, True)
