"""Test cases for statistical distributions and their properties.
This module provides a set of unit tests for various statistical distributions,
including their string representation, estimators, samplers, and encoders.
It includes tests for:
- String evaluation of distributions
- Estimators and their factories
- Samplers and their repeatability
- Log density calculations
- Sequence encoders and their compatibility with distributions
- Estimation and sequence estimation using empirical KL divergence
- Initialization and update methods for accumulators
- Type checking for keys and data"""

# pylint: disable=duplicate-code,eval-used,wildcard-import
# pylint: disable=unused-wildcard-import,line-too-long,broad-exception-caught

import abc
import unittest
from typing import Any, cast

import numpy as np
import pytest

from dmx.stats import *
from dmx.stats import DataSequenceEncoder, SequenceEncodableProbabilityDistribution
from dmx.utils.estimation import empirical_kl_divergence


def str_eval_test(dist: Any) -> bool:
    dist2 = eval(str(dist))
    return bool(dist == dist2)


def estimator_test(dist: Any, est: Any) -> bool:
    # pseudo_count should be passed on estimator call
    return bool(dist.estimator() == est)


def dist_to_encoder_test(dist: Any, encoder: Any) -> bool:
    return bool(dist.dist_to_encoder() == encoder)


def sampler_repeat_test(
    dist: SequenceEncodableProbabilityDistribution,
) -> tuple[bool, list[bool]]:
    """
    Test the repeatability of the sampler for a given distribution.

    This function tests whether the samples generated by the distribution's sampler
    are consistent when the same seed is used multiple times.

    Args:
        dist (SequenceEncodableProbabilityDistribution): The distribution instance to test,
            which must have a `sampler` method.

    Returns:
        tuple: A tuple where the first element is a boolean indicating if the sampler
               is repeatable, and the second element is a list of results for each seed.
    """
    seeds = [1, 2, 3]
    sz = 20
    rv: list[bool] = []
    for seed in seeds:
        s = dist.sampler(seed)
        d1 = s.sample(size=sz)
        s = dist.sampler(seed)
        d2 = s.sample(size=sz)

        is_same = [u[0] == u[1] for u in zip(map(str, d1), map(str, d2))]
        rv.append(all(is_same))

    return all(rv), rv


def log_density_test(
    dist: SequenceEncodableProbabilityDistribution, encoder: DataSequenceEncoder
) -> tuple[bool, str]:
    """
    Test the log density function for a given distribution.

    This function tests that the log density values for a set of samples generated
    by the distribution's sampler match the values computed using `seq_log_density`.

    Args:
        dist (SequenceEncodableProbabilityDistribution): The distribution instance to test.

    Returns:
        tuple: A tuple where the first element is a boolean indicating whether
               the log density values are consistent, and the second element
               is the maximum discrepancy between the calculated values.
    """
    seeds = [1, 2, 3]
    sz = 20
    rv: list[float] = []
    for seed in seeds:
        s = dist.sampler(seed)
        data = s.sample(size=sz)
        try:
            enc_data = encoder.seq_encode(data)
        except Exception:
            return False, "encoder.seq_encode(data)"
        seq_ll = dist.seq_log_density(enc_data)
        for i in range(sz):
            if seq_ll[i] == 0:
                seq_ll[i] = np.abs(dist.log_density(data[i]))
            else:
                seq_ll[i] = np.abs(seq_ll[i] - dist.log_density(data[i])) / np.abs(
                    seq_ll[i]
                )

        rv.append(max(seq_ll))

    return max(rv) < 1.0e-14, "max(rv) test"


def estimator_factory_test(x: Any) -> bool:
    est, factory = x
    rv = est.accumulator_factory()
    return bool(rv == factory)


def factory_make_test(x: Any) -> bool:
    factory, acc_ = x
    acc = factory.make()
    return bool(acc == acc_)


def acc_to_encoder_test(x: Any) -> bool:
    acc, encoder = x
    return bool(acc.acc_to_encoder() == encoder)


def estimation_test(
    dist: SequenceEncodableProbabilityDistribution, encoder: DataSequenceEncoder
) -> tuple[bool, list[list[float]]]:
    """
    Test the estimation of a distribution using empirical KL divergence.

    This function tests whether the empirical KL divergence between the distribution
    and its estimator decreases as the sample size increases.

    Args:
        dist (SequenceEncodableProbabilityDistribution): The distribution instance to test, which
            must have a `sampler` method and an `estimator` method.

    Returns:
        tuple: A tuple where the first element is a boolean indicating whether the
               estimation improved as sample size increased, and the second element
               is a list of KL divergence values for each sample size.
    """
    seeds = [1, 2, 3, 4]
    szs = [50, 500, 5000]
    rv: list[bool] = []

    akld: list[list[float]] = []
    for seed in seeds:
        kld: list[float] = []
        better: list[bool] = []
        for sz in szs:
            data = dist.sampler(seed).sample(size=sz)
            est = dist.estimator()
            enc_data = seq_encode(data, encoder=encoder)
            est_dist = estimate(data, est, dist)

            emp_kld, _, _ = empirical_kl_divergence(dist, est_dist, enc_data)

            if len(kld) > 0:
                better.append(kld[-1] >= emp_kld)

            kld.append(emp_kld)
        akld.append(kld)
        rv.append(all(better))

    akld_mean = np.mean(akld, axis=0)
    passed = bool(np.all(akld_mean[1:] <= akld_mean[:-1]))

    return passed, akld


def seq_estimation_test(
    dist: SequenceEncodableProbabilityDistribution, encoder: DataSequenceEncoder
) -> tuple[bool, list[list[float]]]:
    """
    Test the sequence estimation of a distribution using empirical KL divergence.

    This function tests whether the empirical KL divergence between the distribution
    and its sequence estimator decreases as the sample size increases.

    Args:
        dist (SequenceEncodableProbabilityDistribution): The distribution instance to test,
            which must have a `sampler` method and an estimator capable of sequence estimation.

    Returns:
        tuple: A tuple where the first element is a boolean indicating whether the
            sequence estimation improved as sample size increased, and the second
            element is a list of KL divergence values for each sample size.
    """
    seeds = [1, 2, 3, 4]
    szs = [50, 500, 5000]
    rv: list[bool] = []

    akld: list[list[float]] = []
    for seed in seeds:
        kld: list[float] = []
        better: list[bool] = []
        for sz in szs:
            data = dist.sampler(seed).sample(size=sz)
            est = dist.estimator()
            enc_data = seq_encode(data, encoder=encoder)
            est_dist = seq_estimate(enc_data, est, dist)

            emp_kld, _, _ = empirical_kl_divergence(dist, est_dist, enc_data)

            if len(kld) > 0:
                better.append(kld[-1] >= emp_kld)

            kld.append(emp_kld)
        akld.append(kld)
        rv.append(all(better))

    akld_mean = np.mean(akld, axis=0)
    passed = bool(np.all(akld_mean[1:] <= akld_mean[:-1]))

    return passed, akld


def initialize_test(dist: Any, encoder: Any) -> tuple[bool, list[bool]]:
    seeds = [1, 2, 3]
    sz = 1000
    rv: list[bool] = []
    for seed in seeds:
        data = dist.sampler(seed=seed).sample(sz)
        enc_data = encoder.seq_encode(data)

        est = dist.estimator()

        idata = iter(data)
        acc0 = est.accumulator_factory().make()
        rng = np.random.RandomState(seed)

        for _, x in enumerate(idata):
            acc0.initialize(x, 1.0, rng)
        v0 = acc0.value()

        acc1 = est.accumulator_factory().make()
        rng = np.random.RandomState(seed)

        acc1.seq_initialize(enc_data, np.ones(len(data)), rng)
        v1 = acc1.value()
        d0 = est.estimate(None, v0)
        d1 = est.estimate(None, v1)

        ekld = empirical_kl_divergence(d0, d1, [(sz, enc_data)])
        rv.append(np.abs(ekld[0]) < 1.0e-1)

    return bool(np.all(rv)), rv


def seq_update_test(dist: Any, encoder: Any) -> tuple[bool, list[bool]]:
    seeds = [1, 2, 3]
    sz = 1000
    rv: list[bool] = []
    for seed in seeds:
        data = dist.sampler(seed=seed).sample(sz)
        enc_data = [(sz, encoder.seq_encode(data))]

        est = dist.estimator()
        rng = np.random.RandomState(seed)
        prev_estimate = seq_initialize(enc_data, est, rng)
        updated_estimate = seq_estimate(enc_data, est, prev_estimate)

        ll_prev = np.sum(prev_estimate.seq_log_density(enc_data[0][1]))
        ll = np.sum(updated_estimate.seq_log_density(enc_data[0][1]))
        log_diff = ll - ll_prev
        rv.append(log_diff >= 0)

    return bool(np.all(rv)), rv


class StatsTestClass(unittest.TestCase, metaclass=abc.ABCMeta):
    """
    Abstract class for Binomial test cases.
    Provides common test methods for subclasses to inherit.
    Subclasses must implement the `setUp` method to provide specific setup logic.
    """

    eval_dists: list[Any]
    dist_est: list[Any]
    dist_encoder: list[Any]
    sampler_dist: SequenceEncodableProbabilityDistribution
    density_dist_encoder: list[Any]
    est_factory: list[Any]
    factory_acc: list[Any]
    acc_encoder: list[Any]
    type_check_data: list[Any]
    type_check_keys: list[Any]

    @abc.abstractmethod
    def setUp(self) -> None:
        """
        Abstract method for setting up test data.
        Subclasses must implement this method.
        """
        # self.eval_dists
        # self.dist_est
        # self.dist_encoder
        # self.sampler_dist
        # self.density_dist_encoder
        # self.est_factory
        # self.factory_acc
        # self.acc_encoder

        raise NotImplementedError

    def test_01_str_eval(self) -> None:
        for dist in self.eval_dists:
            self.assertTrue(str_eval_test(dist))

    @pytest.mark.dependency(name="estimator")
    def test_02_estimator(self) -> None:
        for x in self.dist_est:
            rv = estimator_test(*x)
            self.assertTrue(rv)

    @pytest.mark.dependency(name="dist_to_encoder")
    def test_03_dist_to_encoder(self) -> None:
        for dist, encoder in self.dist_encoder:
            self.assertTrue(dist_to_encoder_test(dist, encoder))

    @pytest.mark.dependency(name="sampler")
    def test_04_sampler(self) -> None:
        res = sampler_repeat_test(self.sampler_dist)
        self.assertTrue(res[0], str(res[1]))

    @pytest.mark.dependency(depends=["sampler"], name="log_density")
    def test_05_log_density(self) -> None:
        for x in self.density_dist_encoder:
            res = log_density_test(*x)
            self.assertTrue(res[0], str(res[1]))

    @pytest.mark.dependency(name="estimator_factory")
    def test_06_estimator_factory(self) -> None:
        for est_factory in self.est_factory:
            rv = estimator_factory_test(est_factory)
            self.assertTrue(rv)

    @pytest.mark.dependency(name="factory_make")
    def test_07_factory_make(self) -> None:
        for x in self.factory_acc:
            rv = factory_make_test(x)
            self.assertTrue(rv)

    @pytest.mark.dependency(name="acc_to_encoder")
    def test_08_acc_to_encoder(self) -> None:
        for x in self.acc_encoder:
            rv = acc_to_encoder_test(x)
            self.assertTrue(rv)

    @pytest.mark.dependency(
        depends=["estimator", "log_density", "estimator_factory", "factory_make"]
    )
    def test_09_seq_update(self) -> None:
        for x in self.density_dist_encoder:
            res = seq_update_test(*x)
            self.assertTrue(res[0], str(res[1]))

    # @pytest.mark.dependency(depends=["estimator", "log_density", "estimator_factory", "factory_make"])
    # def test_09_estimation(self) -> None:
    #     for x in self.density_dist_encoder:
    #         res = estimation_test(*x)
    #         self.assertTrue(res[0], str(res[1]))

    # @pytest.mark.dependency(depends=["estimator", "log_density", "estimator_factory", "factory_make"])
    # def test_11_initialize(self) -> None:
    #     for x in self.density_dist_encoder:
    #         res = initialize_test(*x)
    #         self.assertTrue(res[0], str(res[1]))
